apiVersion: batch/v1
kind: Job
metadata:
  name: aws-blog-scraper
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: scraper
        image: polack27/aws-blog-scraper:latest
        command: ["python3", "aws_blog_scrap.py"]
      restartPolicy: Never
