apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base
images:
  - name: polack27/aws-blog-scraper
    newTag: "1.0"
configMapGenerator:
  - name: "cm-scraper"
    files:
      - config.json
secretGenerator:
  - name: "s3secret"
    envs:
      - "mysecret.txt"
patches:
  - patch: |-
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: aws-blog-scraper
      spec:
        template:
          spec:
            containers:
              - name: scraper
                envFrom:
                  - secretRef:
                    name: s3secret
                volumeMounts:
                  - name: scrapper-config
                    mountPath: /opt/blog_scrapper/config.json
                    subPath: config.json
            volumes:
              - name: scrapper-config
                configMap:
                  name: cm-scraper